services:
  - type: web
    name: mtg-chroma
    env: docker
    plan: free
    disk:
      name: chroma-persist
      mountPath: /data
      sizeGB: 2
    autoDeploy: true
    startCommand: python -m chromadb run --host 0.0.0.0 --port 8000 --path /data